### ISSUE TITLE
Suggestion: Add license

### ISSUE THREAD

**Issue by maxiimilian** [nprezant/orbits#21]
This is a really cool project! I made a fork because I would like to use it to visualise some of the orbit mechanics problems I am working on. Maybe I'll add a way to load orbits from CSV files from disks.

Anyway, to make this a smooth experience, I would suggest that you add a license to this project :)

**Comment by nprezant** [comment]
Thanks for reaching out! Persisting orbits would definitely be a useful addition.

I'll go ahead and add a license

Feel free to ask if you run into issues or have other questions!
